### ISSUE TITLE
white lines visible on the iframe

### ISSUE THREAD

**Issue by barroco** [ebu/eis-player#2]
@martinproky wrote:

> Hi, please is possible to shift up and left the slideshow? We have the black page with our player and here is clear white lines up and left. On the white pages is it ok, but on the black pages it looks bad.

**Comment by barroco** [comment]
@martinproky, do you plan to integrate the component or the iframe?
Thanks,

**Comment by martinproky** [comment]
We will integrate the iframe

**Comment by barroco** [comment]
@martinproky you can use the following tag to integrate the component:

`<iframe id='vis-player' src="http://eis-static.ebu.io/prod/signals/eis-rozhlas-cz.html" scrolling="no" seamless="seamless"/>`

Full example available here: https://github.com/ebu/eis-player/blob/develop/iframe/signals/rozhlas-cz.html

Let me know if you need something else

**Comment by martinproky** [comment]
I have the problem with the iframe. On the url http://eis-static.ebu.io/prod/signals/eis-rozhlas-cz.html does not work change of the pictures like here: http://eis-static.ebu.io/prod/eis-player.html

What player is right? Will you repair it?
