### ISSUE TITLE
Link on images

### ISSUE THREAD

**Issue by coinchon** [ebu/eis-player#4]
Hello,

When clicking on the player image at http://www.radio3net.ro/zurich_european_athletics-14058#.U-iiG54XZu1

It leads to a new page with the player only and then a second click must be made on this new page to go the linked page.

**Comment by mhabegger** [comment]
On Safari one click is sufficient.
What browser did you use ?

**Comment by coinchon** [comment]
I used Safari, but I think I spotted the problem. These are my privacy plugins and "no script" that made the problem it seems.
